# Generated by Django 5.1 on 2024-08-08 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
                ('revenue', models.CharField(max_length=255)),
                ('employees', models.CharField(max_length=255)),
                ('industry', models.CharField(max_length=255)),
            ],
        ),
    ]
