# Generated by Django 5.1 on 2024-08-08 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0003_districts'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Districts',
        ),
    ]
