# Generated by Django 5.1 on 2024-08-08 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0004_delete_districts'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
