# Generated by Django 5.1 on 2024-08-08 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0006_city'),
    ]

    operations = [
        migrations.RenameField(
            model_name='city',
            old_name='name',
            new_name='placename',
        ),
    ]
