# Generated by Django 5.1 on 2024-08-09 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0007_rename_name_city_placename'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='placename',
        ),
        migrations.AddField(
            model_name='city',
            name='city',
            field=models.CharField(default='Unknown', max_length=255),
        ),
        migrations.AddField(
            model_name='city',
            name='country',
            field=models.CharField(default='Unknown Country', max_length=255),
        ),
        migrations.AlterField(
            model_name='city',
            name='latitude',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='city',
            name='longitude',
            field=models.CharField(max_length=50),
        ),
    ]
